import type { LessonSection, ReviewCard, Skill } from "../types/geometry";

const f = String.raw;

export const skills: Skill[] = [
  {
    id: "fundamentals",
    title: "Fundamentos",
    shortTitle: "Fundamentos",
    type: "definition",
    prerequisites: [],
    description: "Objetos geométricos, medidas e linguagem rigorosa.",
    lessonId: "fundamentals",
  },
  {
    id: "segments-angles",
    title: "Segmentos e ângulos",
    shortTitle: "Segmentos e ângulos",
    type: "definition",
    prerequisites: ["fundamentals"],
    description: "Ponto médio, classes de ângulos, bissetriz e OPV.",
    lessonId: "segments-angles",
  },
  {
    id: "triangles",
    title: "Triângulos",
    shortTitle: "Triângulos",
    type: "definition",
    prerequisites: ["segments-angles"],
    description: "Definição e classificações por lados e ângulos.",
    lessonId: "triangles",
  },
  {
    id: "congruence",
    title: "Congruência de triângulos",
    shortTitle: "Congruência",
    type: "definition",
    prerequisites: ["triangles"],
    description: "Correspondência ordenada entre vértices, lados e ângulos.",
    lessonId: "congruence",
  },
  {
    id: "lal",
    title: "Postulado LAL",
    shortTitle: "LAL",
    type: "postulate",
    prerequisites: ["congruence"],
    description: "Dois lados e o ângulo compreendido determinam o triângulo.",
    asset: "lal",
    lessonId: "lal",
  },
  {
    id: "isosceles",
    title: "Teorema do triângulo isósceles",
    shortTitle: "Isósceles",
    type: "theorem",
    prerequisites: ["lal"],
    description: "Lados congruentes implicam ângulos da base congruentes.",
    asset: "isosceles-base",
    lessonId: "isosceles",
  },
  {
    id: "ala",
    title: "Teorema ALA",
    shortTitle: "ALA",
    type: "theorem",
    prerequisites: ["lal", "isosceles"],
    description: "Um lado e seus dois ângulos adjacentes determinam o triângulo.",
    asset: "ala",
    lessonId: "ala",
  },
  {
    id: "inverse-isosceles",
    title: "Inverso do isósceles",
    shortTitle: "2 ângulos ⇒ isósceles",
    type: "corollary",
    prerequisites: ["ala"],
    description: "Dois ângulos congruentes implicam lados opostos congruentes.",
    asset: "isosceles-inverso",
    lessonId: "isosceles",
  },
  {
    id: "lll",
    title: "Teorema LLL",
    shortTitle: "LLL",
    type: "theorem",
    prerequisites: ["ala", "inverse-isosceles"],
    description: "Três lados ordenadamente congruentes determinam o triângulo.",
    asset: "lll",
    lessonId: "lll",
  },
  {
    id: "cevians",
    title: "Cevianas",
    shortTitle: "Cevianas",
    type: "definition",
    prerequisites: ["triangles"],
    description: "Segmentos que partem de um vértice rumo ao lado oposto.",
    lessonId: "cevians",
  },
  {
    id: "median-bisector-altitude",
    title: "Mediana, bissetriz e altura",
    shortTitle: "Três cevianas",
    type: "definition",
    prerequisites: ["cevians"],
    description: "Ponto médio, divisão angular e perpendicularidade.",
    asset: "mediana",
    lessonId: "cevians",
  },
  {
    id: "isosceles-cevians",
    title: "Cevianas no isósceles",
    shortTitle: "Resultado especial",
    type: "theorem",
    prerequisites: ["lal", "isosceles", "median-bisector-altitude"],
    description: "No vértice principal, bissetriz, mediana e altura coincidem.",
    asset: "isosceles-especial",
    lessonId: "special-isosceles",
  },
  {
    id: "exterior-angle",
    title: "Ângulo externo",
    shortTitle: "Ângulo externo",
    type: "definition",
    prerequisites: ["segments-angles", "triangles"],
    description: "Um lado e o prolongamento do lado adjacente.",
    lessonId: "exterior-angle",
  },
];

export const lessons: LessonSection[] = [
  {
    id: "fundamentals",
    skillId: "fundamentals",
    eyebrow: "Capítulo I · Linguagem",
    title: "Objetos não são números",
    summary: "Comece distinguindo o segmento geométrico de sua medida — uma separação pequena na escrita, decisiva no raciocínio.",
    estimatedMinutes: 6,
    blocks: [
      {
        id: "segment-object",
        type: "definition",
        title: "Segmento e medida",
        body: [
          "O segmento é o objeto geométrico formado pelos pontos entre A e B, incluindo as extremidades.",
          "A medida é um número não negativo associado ao segmento. Neste curso, AB denota a medida, enquanto a barra denota o objeto.",
        ],
        formulas: [f`\text{segmento: }\overline{AB}`, f`\text{medida: }AB\;\text{ ou }\;m(\overline{AB})`],
        callout: "Evite escrever como padrão “segmento = 2 cm”. Escreva AB = 2 cm ou m(‾AB) = 2 cm.",
      },
      {
        id: "midpoint",
        type: "definition",
        title: "Ponto médio",
        body: ["M é ponto médio de AB quando pertence ao segmento e divide esse segmento em duas partes congruentes."],
        formulas: [f`M\in\overline{AB}`, f`\overline{AM}\cong\overline{MB}`],
        callout: "As duas condições são necessárias: pertencimento e congruência.",
      },
    ],
  },
  {
    id: "segments-angles",
    skillId: "segments-angles",
    eyebrow: "Capítulo II · Ângulos",
    title: "Ângulos e relações fundamentais",
    summary: "Classifique, compare e justifique ângulos sem depender da aparência do desenho.",
    estimatedMinutes: 12,
    blocks: [
      {
        id: "angle-definition",
        type: "definition",
        title: "O que é um ângulo?",
        body: ["Um ângulo é a reunião de duas semirretas de mesma origem. Em ∠AOB, O é o vértice; OA e OB são seus lados."],
        formulas: [f`\angle AOB`],
      },
      {
        id: "angle-types",
        type: "comparison",
        title: "Agudo, reto e obtuso",
        body: ["Agudo mede menos de 90°; reto mede 90°; obtuso mede mais de 90° e menos de 180°."],
        formulas: [f`0^\circ<\alpha<90^\circ`, f`\alpha=90^\circ`, f`90^\circ<\alpha<180^\circ`],
      },
      {
        id: "complements",
        type: "definition",
        title: "Complementares e suplementares",
        body: ["Ângulos complementares somam 90°; suplementares somam 180°."],
        formulas: [f`\alpha+\beta=90^\circ`, f`\operatorname{comp}(\alpha)=90^\circ-\alpha`, f`\alpha+\beta=180^\circ`, f`\operatorname{sup}(\alpha)=180^\circ-\alpha`],
      },
      {
        id: "vertical-angles",
        type: "proposition",
        title: "Opostos pelo vértice são congruentes",
        body: [
          "Os pares ∠AOB e ∠COD são suplementares ao mesmo ângulo ∠BOD.",
          "Subtraindo m(∠BOD) de ambos os membros das duas igualdades, restam medidas iguais.",
        ],
        formulas: [f`m(\angle AOB)+m(\angle BOD)=180^\circ`, f`m(\angle COD)+m(\angle BOD)=180^\circ`, f`\therefore\;\angle AOB\cong\angle COD`],
      },
      {
        id: "angle-bisector",
        type: "definition",
        title: "Bissetriz de um ângulo",
        body: ["A bissetriz é a semirreta interna que divide o ângulo em dois ângulos congruentes."],
        formulas: [f`OC\text{ bissetriz de }\angle AOB\Rightarrow\angle AOC\cong\angle COB`],
      },
    ],
  },
  {
    id: "triangles",
    skillId: "triangles",
    eyebrow: "Capítulo III · Formas",
    title: "Triângulos e classificações",
    summary: "Nomeie os elementos do triângulo e use classificações com uma convenção explícita.",
    estimatedMinutes: 8,
    blocks: [
      {
        id: "triangle-definition",
        type: "definition",
        title: "Triângulo",
        body: ["Dados três pontos A, B e C não colineares, o triângulo ABC é formado pelos segmentos AB, BC e AC. Seus vértices são A, B, C e seus ângulos internos são ∠A, ∠B, ∠C."],
        formulas: [f`\triangle ABC`, f`\overline{AB},\;\overline{BC},\;\overline{AC}`],
      },
      {
        id: "side-classes",
        type: "comparison",
        title: "Classificação pelos lados",
        body: ["Equilátero: três lados congruentes. Isósceles: pelo menos dois lados congruentes. Escaleno: nenhum par de lados congruentes."],
        callout: "Adotamos a convenção inclusiva: todo equilátero é um caso particular de isósceles. Outros materiais podem reservar “isósceles” para exatamente dois lados congruentes.",
      },
      {
        id: "angle-classes",
        type: "comparison",
        title: "Classificação pelos ângulos",
        body: ["Acutângulo: três ângulos agudos. Retângulo: um ângulo reto. Obtusângulo: um ângulo obtuso."],
      },
    ],
  },
  {
    id: "congruence",
    skillId: "congruence",
    eyebrow: "Capítulo IV · Correspondência",
    title: "Congruência é uma ordem com significado",
    summary: "A ordem dos vértices registra exatamente quais lados e ângulos se correspondem.",
    estimatedMinutes: 10,
    blocks: [
      {
        id: "congruence-definition",
        type: "definition",
        title: "Congruência de triângulos",
        body: ["Dois triângulos são congruentes quando há uma correspondência biunívoca entre seus vértices que preserva lados e ângulos correspondentes."],
        formulas: [f`\triangle ABC\cong\triangle DEF`],
      },
      {
        id: "ordered-correspondence",
        type: "example",
        title: "Correspondência ordenada",
        body: ["A primeira letra corresponde à primeira, a segunda à segunda, e a terceira à terceira. Portanto, a ordem não é estética."],
        formulas: [f`A\leftrightarrow D,\quad B\leftrightarrow E,\quad C\leftrightarrow F`, f`AB\leftrightarrow DE,\quad BC\leftrightarrow EF,\quad AC\leftrightarrow DF`],
        callout: "Congruência preserva forma e tamanho; semelhança preserva forma, mas pode alterar o tamanho.",
      },
    ],
  },
  {
    id: "lal",
    skillId: "lal",
    eyebrow: "Capítulo V · Primeiro critério",
    title: "Postulado LAL",
    summary: "Dois lados e o ângulo compreendido entre eles fixam um único triângulo, salvo posição no plano.",
    estimatedMinutes: 9,
    blocks: [
      {
        id: "lal-statement",
        type: "postulate",
        title: "Lado–Ângulo–Lado",
        body: ["Se dois triângulos têm ordenadamente congruentes dois lados e o ângulo compreendido entre eles, então os triângulos são congruentes."],
        formulas: [f`AB\cong DE`, f`AC\cong DF`, f`\angle BAC\cong\angle EDF`, f`\therefore\;\triangle BAC\cong\triangle EDF`],
        asset: "lal",
      },
      {
        id: "lal-included",
        type: "warning",
        title: "O ângulo precisa estar entre os lados",
        body: ["AB e AC se encontram em A; logo o ângulo compreendido é ∠BAC. Conhecer outro ângulo produz a configuração LLA, que pode admitir dois triângulos diferentes e não é critério geral de congruência."],
        callout: "Teste rápido: os dois lados conhecidos encostam no vértice do ângulo marcado?",
      },
    ],
  },
  {
    id: "isosceles",
    skillId: "isosceles",
    eyebrow: "Capítulo VI · Primeiro teorema",
    title: "Triângulo isósceles",
    summary: "Use LAL para transformar a igualdade dos lados em igualdade dos ângulos da base.",
    estimatedMinutes: 12,
    blocks: [
      {
        id: "isosceles-theorem",
        type: "theorem",
        title: "Teorema dos ângulos da base",
        body: ["Em um triângulo isósceles, os ângulos opostos aos lados congruentes — os ângulos da base — são congruentes."],
        formulas: [f`AB\cong AC\Rightarrow\angle ABC\cong\angle BCA`],
        asset: "isosceles-base",
        callout: "Hipótese: AB ≅ AC. Conclusão: ∠B ≅ ∠C. A base é BC.",
      },
      {
        id: "equilateral-corollary",
        type: "corollary",
        title: "Corolário do equilátero",
        body: ["Se os três lados são congruentes, podemos aplicar o teorema do isósceles usando diferentes pares de lados. Assim, os três ângulos são congruentes."],
        formulas: [f`AB\cong BC\cong CA\Rightarrow\angle A\cong\angle B\cong\angle C`],
      },
      {
        id: "inverse-corollary",
        type: "corollary",
        title: "Inverso do isósceles",
        body: ["Depois de estabelecer ALA, obtemos a recíproca: se dois ângulos de um triângulo são congruentes, os lados opostos também são congruentes."],
        formulas: [f`\angle B\cong\angle C\Rightarrow AB\cong AC`],
        asset: "isosceles-inverso",
      },
    ],
  },
  {
    id: "ala",
    skillId: "ala",
    eyebrow: "Capítulo VII · Prova indireta",
    title: "Teorema ALA",
    summary: "Um lado e os dois ângulos a ele adjacentes bastam; a prova reduz a situação ao postulado LAL.",
    estimatedMinutes: 14,
    blocks: [
      {
        id: "ala-statement",
        type: "theorem",
        title: "Ângulo–Lado–Ângulo",
        body: ["Se dois triângulos têm ordenadamente congruentes um lado e os dois ângulos a ele adjacentes, então são congruentes."],
        formulas: [f`AB\cong DE`, f`\angle A\cong\angle D`, f`\angle B\cong\angle E`, f`\therefore\;\triangle ABC\cong\triangle DEF`],
        asset: "ala",
      },
      {
        id: "ala-proof-preview",
        type: "example",
        title: "Estratégia da demonstração",
        body: ["Suponha AC < DF e marque F′ em DF com DF′ ≅ AC. LAL torna △BAC congruente a △EDF′. Isso força o mesmo ângulo em E que a hipótese atribui à semirreta EF; se F′ ≠ F, duas semirretas distintas no mesmo semiplano formariam o mesmo ângulo com ED, uma contradição."],
        formulas: [f`AC<DF`, f`DF'\cong AC`, f`\triangle BAC\cong\triangle EDF'`],
        callout: "Abra Provas para revelar a justificativa completa, passo a passo.",
      },
    ],
  },
  {
    id: "lll",
    skillId: "lll",
    eyebrow: "Capítulo VIII · Terceiro critério",
    title: "Teorema LLL",
    summary: "Os três comprimentos correspondentes determinam o triângulo; a prova complementar usa resultados já desbloqueados.",
    estimatedMinutes: 13,
    blocks: [
      {
        id: "lll-statement",
        type: "theorem",
        title: "Lado–Lado–Lado",
        body: ["Se dois triângulos têm ordenadamente congruentes os três lados, então são congruentes."],
        formulas: [f`AB\cong DE`, f`AC\cong DF`, f`BC\cong EF`, f`\therefore\;\triangle ABC\cong\triangle DEF`],
        asset: "lll",
        callout: "A prova exibida no caderno de provas é identificada como demonstração complementar clássica; nenhuma passagem é atribuída ao professor.",
      },
    ],
  },
  {
    id: "cevians",
    skillId: "cevians",
    eyebrow: "Capítulo IX · Segmentos notáveis",
    title: "Cevianas: três condições diferentes",
    summary: "Mediana, bissetriz e altura partem de um vértice, mas cada uma responde a uma hipótese distinta.",
    estimatedMinutes: 12,
    blocks: [
      {
        id: "cevian-definition",
        type: "definition",
        title: "Cevianas",
        body: ["Neste curso, chamamos ceviana o segmento que parte de um vértice do triângulo até o lado oposto. Em definições mais amplas, o ponto final pode estar na reta suporte do lado."],
      },
      {
        id: "median",
        type: "definition",
        title: "Mediana ⇒ ponto médio",
        body: ["AM é mediana relativa ao vértice A — ou ao lado BC — quando M é o ponto médio de BC."],
        formulas: [f`M\in\overline{BC}`, f`\overline{BM}\cong\overline{MC}`],
        asset: "mediana",
      },
      {
        id: "internal-bisector",
        type: "definition",
        title: "Bissetriz ⇒ ângulos congruentes",
        body: ["AD é bissetriz interna relativa a A quando D pertence a BC e divide ∠A em dois ângulos congruentes."],
        formulas: [f`D\in\overline{BC}`, f`\angle BAD\cong\angle DAC`],
        asset: "bissetriz",
        callout: "Não conclua BD = DC apenas porque AD é bissetriz.",
      },
      {
        id: "altitude",
        type: "definition",
        title: "Altura ⇒ perpendicularidade",
        body: ["A altura relativa a A é o segmento perpendicular à reta que contém o lado oposto. Em triângulos obtusângulos, uma altura pode ficar fora do triângulo."],
        formulas: [f`AD\perp BC`],
        asset: "altura",
      },
      {
        id: "cevians-comparison",
        type: "comparison",
        title: "Não confunda as hipóteses",
        body: ["Mediana verifica ponto médio. Bissetriz verifica igualdade de ângulos. Altura verifica 90°. Em um triângulo genérico, são segmentos distintos."],
        formulas: [f`\text{mediana}\ne\text{bissetriz}\ne\text{altura}`],
      },
    ],
  },
  {
    id: "special-isosceles",
    skillId: "isosceles-cevians",
    eyebrow: "Capítulo X · Resultado especial",
    title: "Quando as três cevianas coincidem",
    summary: "A coincidência não é geral: ela ocorre para a ceviana do vértice principal de um triângulo isósceles.",
    estimatedMinutes: 12,
    blocks: [
      {
        id: "special-result",
        type: "theorem",
        title: "Bissetriz = mediana = altura",
        body: ["Se AB ≅ AC e AD é a bissetriz do ângulo principal, então os triângulos ABD e ACD são congruentes por LAL: lado, reflexividade de AD e os ângulos da bissetriz."],
        formulas: [f`AB\cong AC`, f`AD\cong AD`, f`\angle BAD\cong\angle CAD`, f`\triangle ABD\cong\triangle ACD`],
        asset: "isosceles-especial",
      },
      {
        id: "special-consequences",
        type: "corollary",
        title: "Duas consequências da congruência",
        body: ["Da correspondência B ↔ C, vem BD ≅ DC, então D é ponto médio e AD é mediana. Também ∠ADB ≅ ∠ADC. Como são adjacentes sobre a reta BC, somam 180°; sendo iguais, cada um mede 90°, logo AD é altura."],
        formulas: [f`BD\cong DC`, f`2m(\angle ADB)=180^\circ`, f`m(\angle ADB)=90^\circ`, f`AD\perp BC`],
        callout: "Este resultado vale apenas nesta configuração especial.",
      },
    ],
  },
  {
    id: "exterior-angle",
    skillId: "exterior-angle",
    eyebrow: "Capítulo XI · Fronteira atual",
    title: "Ângulo externo",
    summary: "Defina o objeto e sua suplementaridade sem antecipar um teorema ainda não estudado.",
    estimatedMinutes: 5,
    blocks: [
      {
        id: "external-definition",
        type: "definition",
        title: "Definição",
        body: ["Um ângulo externo de um triângulo é formado por um lado e pelo prolongamento de um lado adjacente. Se BC é prolongado além de C, o ângulo interno em C e o externo adjacente formam um par linear."],
        formulas: [f`m(\angle C_{\mathrm{interno}})+m(\angle C_{\mathrm{externo}})=180^\circ`],
      },
      {
        id: "next-unlock",
        type: "warning",
        title: "Próximo desbloqueio",
        body: ["O teorema que relaciona a medida do ângulo externo aos dois ângulos internos não adjacentes fica reservado para a próxima etapa. Aqui, usamos apenas a definição e a suplementaridade."],
      },
    ],
  },
];

export const reviewCards: ReviewCard[] = [
  { id: "r-segment", skillId: "fundamentals", concept: "Segmento × medida", definition: "A barra nomeia o objeto; AB sem barra pode nomear sua medida.", formula: f`\overline{AB}\;\text{é objeto};\quad AB\;\text{é medida}`, commonError: "Escrever o segmento como igual a um número com unidade.", question: "Como escrever que a medida é 2 cm?", answer: f`AB=2\,\text{cm}` },
  { id: "r-opv", skillId: "segments-angles", concept: "Ângulos OPV", definition: "Ângulos opostos pelo vértice são congruentes.", formula: f`\angle AOB\cong\angle COD`, commonError: "Usar OPV para ângulos apenas adjacentes.", question: "Qual relação prova OPV?", answer: "Ambos são suplementares ao mesmo ângulo." },
  { id: "r-correspondence", skillId: "congruence", concept: "Correspondência ordenada", definition: "A posição de cada letra registra o vértice correspondente.", formula: f`\triangle ABC\cong\triangle DEF\Rightarrow AC\leftrightarrow DF`, commonError: "Trocar a ordem porque o desenho parece simétrico.", question: "Qual lado corresponde a BC?", answer: f`EF` },
  { id: "r-lal", skillId: "lal", concept: "LAL", definition: "Dois lados e o ângulo compreendido são ordenadamente congruentes.", formula: f`L-\widehat{A}-L`, commonError: "Usar um ângulo que não está entre os lados conhecidos.", question: "Qual vértice contém o ângulo entre AB e AC?", answer: "A" },
  { id: "r-isosceles", skillId: "isosceles", concept: "Teorema do isósceles", definition: "Lados congruentes implicam ângulos opostos congruentes.", formula: f`AB\cong AC\Rightarrow\angle B\cong\angle C`, commonError: "Trocar hipótese e conclusão sem justificar a recíproca.", question: "Qual é a base?", answer: f`BC` },
  { id: "r-ala", skillId: "ala", concept: "ALA", definition: "Um lado e os dois ângulos adjacentes a ele determinam o triângulo.", formula: f`\widehat{A}-L-\widehat{A}`, commonError: "Escolher um lado que não fica entre os ângulos conhecidos.", question: "ALA foi provado usando qual postulado?", answer: "LAL" },
  { id: "r-lll", skillId: "lll", concept: "LLL", definition: "Três lados ordenadamente congruentes implicam triângulos congruentes.", formula: f`L-L-L`, commonError: "Confundir três razões proporcionais com três congruências.", question: "LLL é postulado neste curso?", answer: "Não; é teorema." },
  { id: "r-cevians", skillId: "median-bisector-altitude", concept: "Três cevianas", definition: "Mediana: ponto médio. Bissetriz: ângulos. Altura: perpendicularidade.", formula: f`\text{M}\to\text{meio};\quad\text{B}\to\text{ângulo};\quad\text{A}\to90^\circ`, commonError: "Achar que qualquer uma implica automaticamente as outras.", question: "BD ≅ DC caracteriza qual ceviana AD?", answer: "Mediana" },
];

export function getLesson(id: string) {
  return lessons.find((lesson) => lesson.id === id) ?? lessons[0];
}

export function getSkill(id: string) {
  return skills.find((skill) => skill.id === id) ?? skills[0];
}
