import type { Proof } from "../types/geometry";

const f = String.raw;

export const proofs: Proof[] = [
  {
    id: "vertical-angles-proof",
    title: "Ângulos opostos pelo vértice",
    skillId: "segments-angles",
    statement: "Ângulos opostos pelo vértice são congruentes.",
    formula: f`\angle AOB\cong\angle COD`,
    badge: "proposition",
    steps: [
      { id: "opv-1", kind: "hypothesis", label: "Par linear I", formula: f`m(\angle AOB)+m(\angle BOD)=180^\circ`, explanation: "A e D estão em semirretas opostas; por isso os ângulos adjacentes formam um ângulo raso." },
      { id: "opv-2", kind: "hypothesis", label: "Par linear II", formula: f`m(\angle COD)+m(\angle BOD)=180^\circ`, explanation: "C e B também estão em semirretas opostas." },
      { id: "opv-3", kind: "inference", label: "Subtração legítima", formula: f`m(\angle AOB)=m(\angle COD)`, explanation: "Subtraímos a mesma quantidade m(∠BOD) dos dois membros das duas igualdades." },
      { id: "opv-4", kind: "conclusion", label: "Conclusão", formula: f`\angle AOB\cong\angle COD`, explanation: "Ângulos com a mesma medida são congruentes." },
    ],
  },
  {
    id: "isosceles-base-proof",
    title: "Ângulos da base no isósceles",
    skillId: "isosceles",
    statement: "Em um triângulo isósceles, os ângulos da base são congruentes.",
    formula: f`AB\cong AC\Rightarrow\angle ABC\cong\angle BCA`,
    badge: "theorem",
    steps: [
      { id: "iso-1", kind: "hypothesis", label: "Hipótese", formula: f`AB\cong AC`, explanation: "O triângulo ABC é isósceles de base BC." },
      { id: "iso-2", kind: "construction", label: "Construção", formula: f`AD\text{ é bissetriz de }\angle BAC`, explanation: "Traçamos a bissetriz interna do ângulo principal, encontrando BC em D." },
      { id: "iso-3", kind: "known-result", label: "Reflexividade", formula: f`AD\cong AD`, explanation: "O segmento AD é lado comum aos dois triângulos." },
      { id: "iso-4", kind: "known-result", label: "Definição de bissetriz", formula: f`\angle BAD\cong\angle DAC`, explanation: "A construção divide o ângulo principal em duas partes congruentes." },
      { id: "iso-5", kind: "inference", label: "Critério LAL", formula: f`\triangle BAD\cong\triangle CAD`, explanation: "Lados AB ↔ AC, AD ↔ AD e o ângulo compreendido BAD ↔ CAD." },
      { id: "iso-6", kind: "conclusion", label: "Correspondência", formula: f`\angle ABD\cong\angle ACD`, explanation: "B ↔ C na congruência. Como D pertence a BC, esses são precisamente os ângulos da base ∠ABC e ∠BCA." },
    ],
  },
  {
    id: "ala-indirect-proof",
    title: "Teorema ALA",
    skillId: "ala",
    statement: "Um lado e os dois ângulos a ele adjacentes, ordenadamente congruentes, implicam triângulos congruentes.",
    formula: f`AB\cong DE,\;\angle A\cong\angle D,\;\angle B\cong\angle E\Rightarrow\triangle ABC\cong\triangle DEF`,
    badge: "theorem",
    steps: [
      { id: "ala-1", kind: "hypothesis", label: "Hipóteses", formula: f`AB\cong DE,\quad\angle A\cong\angle D,\quad\angle B\cong\angle E`, explanation: "O lado AB está entre os dois ângulos conhecidos; o correspondente é DE." },
      { id: "ala-2", kind: "construction", label: "Suposição indireta", formula: f`AC<DF`, explanation: "Se os lados não fossem congruentes, um seria menor. Sem perda de generalidade, supomos AC < DF." },
      { id: "ala-3", kind: "construction", label: "Marcação auxiliar", formula: f`F'\in\overrightarrow{DF}\quad\text{e}\quad DF'\cong AC`, explanation: "Marcamos F′ na semirreta DF com a mesma distância de D que C tem de A." },
      { id: "ala-4", kind: "known-result", label: "Postulado LAL", formula: f`\triangle BAC\cong\triangle EDF'`, explanation: "BA ↔ ED, AC ↔ DF′ e o ângulo compreendido A ↔ D são congruentes." },
      { id: "ala-5", kind: "inference", label: "Ângulos correspondentes", formula: f`\angle ABC\cong\angle DEF'`, explanation: "Pela correspondência B ↔ E da congruência obtida por LAL." },
      { id: "ala-6", kind: "inference", label: "Contradição", formula: f`\angle DEF'\cong\angle DEF`, explanation: "A hipótese também dá ∠ABC ≅ ∠DEF. Se F′ ≠ F, duas semirretas distintas EF′ e EF, no mesmo semiplano, formariam exatamente o mesmo ângulo com ED — contrariando a unicidade da semirreta que realiza uma medida angular dada." },
      { id: "ala-7", kind: "inference", label: "A suposição falha", formula: f`F'=F\quad\Rightarrow\quad AC\cong DF`, explanation: "Logo, não pode ocorrer AC < DF. O caso DF < AC é análogo; resta AC ≅ DF." },
      { id: "ala-8", kind: "conclusion", label: "LAL final", formula: f`\triangle ABC\cong\triangle DEF`, explanation: "Agora AB ↔ DE, AC ↔ DF e o ângulo compreendido A ↔ D são congruentes." },
    ],
  },
  {
    id: "lll-classical-proof",
    title: "Teorema LLL",
    skillId: "lll",
    statement: "Três lados ordenadamente congruentes implicam triângulos congruentes.",
    formula: f`AB\cong DE,\;AC\cong DF,\;BC\cong EF\Rightarrow\triangle ABC\cong\triangle DEF`,
    badge: "theorem",
    complementary: true,
    steps: [
      { id: "lll-1", kind: "hypothesis", label: "Hipóteses", formula: f`AB\cong DE,\quad AC\cong DF,\quad BC\cong EF`, explanation: "As congruências estão na ordem A ↔ D, B ↔ E, C ↔ F." },
      { id: "lll-2", kind: "construction", label: "Cópia angular auxiliar", formula: f`\angle GAB\cong\angle FDE,\quad\angle ABG\cong\angle DEF`, explanation: "No semiplano oposto a C em relação a AB, copiamos em A e B os ângulos de D e E; as semirretas encontram-se em G." },
      { id: "lll-3", kind: "known-result", label: "ALA já estabelecido", formula: f`\triangle GAB\cong\triangle FDE`, explanation: "Os dois ângulos construídos e o lado compreendido AB ↔ DE permitem ALA. Portanto AG ≅ DF e BG ≅ EF." },
      { id: "lll-4", kind: "inference", label: "Dois isósceles", formula: f`AC\cong AG,\quad BC\cong BG`, explanation: "Usamos transitividade com as hipóteses. Assim, ACG e BCG são triângulos isósceles." },
      { id: "lll-5", kind: "known-result", label: "Ângulos da base", formula: f`\angle ACG\cong\angle CGA,\quad\angle BCG\cong\angle CGB`, explanation: "Aplicamos o teorema do triângulo isósceles a ACG e BCG." },
      { id: "lll-6", kind: "inference", label: "Adição de ângulos", formula: f`\angle ACB\cong\angle AGB`, explanation: "Na configuração construída em semiplanos opostos, esses ângulos são somas dos pares congruentes anteriores." },
      { id: "lll-7", kind: "known-result", label: "LAL", formula: f`\triangle ACB\cong\triangle AGB`, explanation: "AC ↔ AG, BC ↔ BG e os ângulos compreendidos C ↔ G são congruentes." },
      { id: "lll-8", kind: "conclusion", label: "Transitividade", formula: f`\triangle ABC\cong\triangle DEF`, explanation: "△ABG já é congruente a △DEF por ALA; combinando as congruências, obtemos o resultado. Esta é uma demonstração complementar clássica, não uma transcrição atribuída à aula." },
    ],
  },
  {
    id: "special-cevian-proof",
    title: "Bissetriz principal no isósceles",
    skillId: "isosceles-cevians",
    statement: "No triângulo isósceles, a bissetriz do vértice principal também é mediana e altura.",
    formula: f`\text{bissetriz}=\text{mediana}=\text{altura}`, 
    badge: "theorem",
    steps: [
      { id: "sp-1", kind: "hypothesis", label: "Isósceles", formula: f`AB\cong AC`, explanation: "ABC é isósceles de base BC." },
      { id: "sp-2", kind: "hypothesis", label: "Bissetriz", formula: f`\angle BAD\cong\angle CAD`, explanation: "AD divide o ângulo principal em partes congruentes." },
      { id: "sp-3", kind: "known-result", label: "Reflexividade", formula: f`AD\cong AD`, explanation: "AD é lado comum." },
      { id: "sp-4", kind: "inference", label: "LAL", formula: f`\triangle ABD\cong\triangle ACD`, explanation: "A correspondência é A ↔ A, B ↔ C, D ↔ D." },
      { id: "sp-5", kind: "inference", label: "Ponto médio", formula: f`BD\cong DC`, explanation: "Lados correspondentes. Como D pertence a BC, D é ponto médio; logo AD é mediana." },
      { id: "sp-6", kind: "inference", label: "Ângulos adjacentes", formula: f`\angle ADB\cong\angle ADC`, explanation: "São ângulos correspondentes e, como B, D, C são colineares, também são suplementares." },
      { id: "sp-7", kind: "inference", label: "Cada ângulo é reto", formula: f`2m(\angle ADB)=180^\circ\Rightarrow m(\angle ADB)=90^\circ`, explanation: "Dois ângulos congruentes cuja soma é 180° medem 90° cada." },
      { id: "sp-8", kind: "conclusion", label: "Resultado desbloqueado", formula: f`AD\perp BC`, explanation: "AD é também altura. A coincidência vale nesta configuração especial, não em um triângulo genérico." },
    ],
  },
];
